### ISSUE TITLE
Request for some more AsciiDoc snippets

### ISSUE THREAD

**Issue by mmuehlfeldRH** [jhradilek/vim-snippets#1]
Can you please add snippets for:

- [application]``
- [citetitle]``
- [function]``
- [guilabel]``
- [gui]``
- [option]``
- [parameter]``
- [systemitem]``

Please also add:
```
[literal,subs="+quotes"]
----
----
```
to support that e. g.  `__variable_text__` in listing blocks will be rendered italic.

Thanks.

**Comment by jhradilek** [comment]
Hi Marc, thank you very much for your request. I added all snippets, except for `guilable` as I am not clear on the difference between that one and `gui`. I know that all of these are derived from DocBook elements, but without also adding `guibutton`, `guimenu`, and others, I feel like having just `gui` is a better option.

In addition to the requested `literal` snippet, I also added `source` for source code blocks.

Please let me know if you are happy with these so that I can close this issue.

**Comment by jhradilek** [comment]
Hi Marc, just so that you know, I just changed the delimiter for `literal` from `----` to `....` to follow the conventions in the Asciidoctor User Manual. Consequently, the snippet now expands to the following:

    [literal,subs="+quotes"]
    ....
    your text here
    ....

**Comment by mmuehlfeldRH** [comment]
I tested the new snippets and they work. Thanks. You can close this request.

I agree that guilabel is not necessary and gui is sufficient.
